### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by theodorusclarence** [tkt-actions/add-issue-links#298]
# Overview

Hi, I got an error with v1.8.1, 

I've also tried downgrading to 1.7.0: It's green, but PR's body is not updated.

Thanks

# Bugs

Not working

## Error Messages

![CleanShot 2023-01-15 at 16 50 08](https://user-images.githubusercontent.com/55318172/212534132-489d79fd-c57e-477e-a8f3-148eb6801685.png)

# Checks
- [ ] Documents
- [ ] Implementations
- [ ] Tests

**Comment by tktcorporation** [comment]
Thanks for the bug report! :bow:
I will investigate the cause and fix it.

**Comment by tktcorporation** [comment]
The problem did not appear to be caused by the code base of this repository.

It appears that GITHUB_TOKEN now restricts the behavior of actions that violate the code owner's intent. An update to the library may have changed the behavior regarding this between 1.7.0 and 1.8.1.
ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by tktcorporation** [comment]
@theodorusclarence 
It does not seem to be caused by the code base of this repository.

It appears that GITHUB_TOKEN now restricts the behavior of actions that violate the code owner's intent. An update to the library may have changed the behavior regarding this between 1.7.0 and 1.8.1.
ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by tktcorporation** [comment]
I have added a section to the README to address that GITHUB_TOKEN permission issue.
https://github.com/tkt-actions/add-issue-links/pull/301/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R33-R35

Please try this solution!!
And let me know if it worked in your environment!

**Comment by theodorusclarence** [comment]
awesome, it works! Thanks!

On my way to update it on https://github.com/theodorusclarence/ts-nextjs-tailwind-starter

**Comment by tktcorporation** [comment]
Than you for the report and using my github action!
